/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sf23.gltf 
Author: Redgrund (https://sketchfab.com/redgrund)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scuderia-ferrari-f1-sf23-2023-ecb0f812bc454331bbe721655b0780ec
Title: Scuderia Ferrari F1 SF23 2023
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/sf23.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Body_PBR_Material}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.Body_PBR_Material}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Body_PBR_Material}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.Body_PBR_Material}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Body_PBR_Material}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.Body_PBR_Material}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.Body_PBR_Material}
        castShadow
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload("/sf23.gltf");
